[package]
name = "blobstream_sn"
version = "0.1.0"

[scripts]
test = "snforge test"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.16.0" }
starknet = "2.5.0"
openzeppelin = { git = "https://github.com/ametel01/cairo-contracts.git", rev = "a46a6b9" }
alexandria_bytes = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "Mainnet"
url = ""
block_id.tag = "Latest"
